# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Butterfish < Formula
  desc "A tool for using LLMs on the command line"
  homepage "https://github.com/bakks/butterfish"
  version "0.3.8"
  license "MIT"
  depends_on :macos

  url "https://github.com/bakks/butterfish/releases/download/v0.3.8/butterfish_0.3.8_darwin_all.tar.gz"
  sha256 "b6a5af5acfb1b70e82c58cc9572daf81e163b666a455425761201a5422d61c5b"

  def install
    bin.install "butterfish"
  end
end
