# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poptop < Formula
  desc "A modern Top command that dynamically charts system metrics in the terminal."
  homepage "https://github.com/bakks/poptop"
  version "0.1.2"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bakks/poptop/releases/download/v0.1.2/poptop_0.1.2_darwin_arm64.tar.gz"
      sha256 "8d039c2d5dd260937123bfe62e18139e7bb7a441dd21d59b93fe6f8fa18e3a96"

      def install
        bin.install "poptop"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bakks/poptop/releases/download/v0.1.2/poptop_0.1.2_darwin_amd64.tar.gz"
      sha256 "953d8ea8e7cae72a87d266bb13d2e83dbad95021e573f012ee96b4e698b378a7"

      def install
        bin.install "poptop"
      end
    end
  end
end
